version: "3.7"
services:
  app:
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - app_port=${APP_PORT}
    ports:
      - ${APP_PORT}:${APP_PORT}

    container_name: ${PROJECT_NAME}_moodle4
    network_mode: host
    volumes:
      - ./moodle400:/var/www/html
      - ./moodledata:/var/www/moodledata:rw
      # - ./.docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    restart: always
  frontend:
    build:
      context: frontend
      target: builder
      dockerfile: frontent.Dockerfile
    ports:
      - 4201:4200
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules
